#!/usr/bin/env python3
"""
Constrained rule-based reconstruction of logical process executions.

This is the first T0 grouping stage after relationship scoring.

Important design choice:
    Do NOT use connected components.

Instead, process each session chronologically and maintain a small set of
"active" logical executions. A new activity can join an execution only when
there is sufficiently strong direct evidence or very close contextual
continuity. Otherwise it starts a new execution/UNKNOWN track.

A logical execution may later become multiple contiguous output segments when
another execution or UNASSIGNED activity interrupts it.

Outputs:
    execution_groups.jsonl
        one logical execution per record, with activity IDs and derived
        contiguous runs.

    segments_candidates.jsonl
        Rule-A-style contiguous segments. The label is the logical execution
        ID for Dataset-A evaluation only; final business labels are a later step.

    grouping_summary.json
        counts and invariant checks.
"""

from __future__ import annotations

import argparse
import json
import sys
import unicodedata
from collections import defaultdict, deque
from datetime import datetime
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Conservative T0 parameters
# ---------------------------------------------------------------------------

# A strong relationship (same entity / explicit trigger) may bridge a longer
# interruption because the object itself provides identity continuity.
STRONG_BRIDGE_MAX_SECONDS = 300.0

# Context-only continuation is deliberately short. This prevents "same Chrome
# window all afternoon" from becoming one giant process.
CONTEXT_CONTINUATION_MAX_SECONDS = 12.0

# Only inspect the most recent members of an execution when looking for a
# relationship edge. This stops long-range chain effects inside a group.
RECENT_MEMBER_LIMIT = 4

# If another execution has a much stronger direct relationship, do not attach
# a context-only activity to a weaker candidate.
STRONG_SCORE_MARGIN = 2

# Context-only relationship must at least satisfy this relationship score.
CONTEXT_SCORE_MIN = 3

# Only these activity types are allowed to be conservative "system-only"
# unassigned noise. We do not classify ordinary APP_SWITCH as non-business.
SYSTEM_TYPES = {"OTHER"}

# Layers that mean the event was generated by the recording/agent itself.
SYSTEM_LAYERS = {"SYSTEM"}


# ---------------------------------------------------------------------------
# Parsing / normalization
# ---------------------------------------------------------------------------

def parse_timestamp(value: Any) -> datetime:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"Invalid timestamp: {value!r}")

    text = value.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"

    dt = datetime.fromisoformat(text)
    if dt.tzinfo is None:
        raise ValueError(f"Timestamp must contain timezone information: {value!r}")
    return dt


def norm(value: Any) -> str:
    if not isinstance(value, str):
        return ""
    return unicodedata.normalize("NFKC", value).strip().casefold()


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(path)

    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_no, raw in enumerate(handle, start=1):
            line = raw.strip()
            if not line:
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"Invalid JSON at {path}:{line_no}: {exc}"
                ) from exc
            if not isinstance(value, dict):
                raise ValueError(f"{path}:{line_no} is not a JSON object.")
            records.append(value)

    if not records:
        raise ValueError(f"{path} contains no records.")

    return records


# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------

def validate_activities(
    records: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    required = {
        "activity_id",
        "session_id",
        "start",
        "end",
        "type",
        "app",
        "window",
        "browser_tab",
        "browser_url",
        "entities",
        "source_layers",
    }

    seen: set[str] = set()
    by_session: dict[str, list[dict[str, Any]]] = defaultdict(list)

    for index, activity in enumerate(records, start=1):
        missing = required - set(activity)
        if missing:
            raise ValueError(
                f"Activity record {index} missing fields: {sorted(missing)}"
            )

        activity_id = activity["activity_id"]
        session_id = activity["session_id"]

        if not isinstance(activity_id, str) or not activity_id:
            raise ValueError(f"Activity record {index}: invalid activity_id.")
        if activity_id in seen:
            raise ValueError(f"Duplicate activity_id: {activity_id}")
        seen.add(activity_id)

        if not isinstance(session_id, str) or not session_id:
            raise ValueError(f"Activity {activity_id}: invalid session_id.")

        start = parse_timestamp(activity["start"])
        end = parse_timestamp(activity["end"])
        if end < start:
            raise ValueError(f"Activity {activity_id}: end before start.")

        if not isinstance(activity["entities"], list):
            raise ValueError(f"Activity {activity_id}: entities must be a list.")
        if not isinstance(activity["source_layers"], list):
            raise ValueError(
                f"Activity {activity_id}: source_layers must be a list."
            )

        activity["_start_dt"] = start
        activity["_end_dt"] = end
        activity["_start_ts"] = start.timestamp()
        activity["_end_ts"] = end.timestamp()
        by_session[session_id].append(activity)

    for session_id, items in by_session.items():
        items.sort(key=lambda a: (a["_start_dt"], a["_end_dt"], a["activity_id"]))

    return dict(by_session)


def build_relationship_index(
    relationships: list[dict[str, Any]],
) -> dict[str, dict[str, dict[str, Any]]]:
    """
    Store every relationship symmetrically:
        index[activity_a][activity_b] = features
    """
    index: dict[str, dict[str, dict[str, Any]]] = defaultdict(dict)

    seen_pairs: set[tuple[str, str]] = set()

    for row_no, relation in enumerate(relationships, start=1):
        a = relation.get("activity_a")
        b = relation.get("activity_b")
        features = relation.get("features")

        if not isinstance(a, str) or not isinstance(b, str):
            raise ValueError(
                f"Relationship {row_no}: activity_a/activity_b must be strings."
            )
        if a == b:
            raise ValueError(f"Relationship {row_no}: self-link {a}.")
        if not isinstance(features, dict):
            raise ValueError(
                f"Relationship {row_no}: missing features object."
            )

        pair = tuple(sorted((a, b)))
        if pair in seen_pairs:
            raise ValueError(
                f"Duplicate relationship pair: {pair[0]} <-> {pair[1]}"
            )
        seen_pairs.add(pair)

        index[a][b] = features
        index[b][a] = features

    return dict(index)


# ---------------------------------------------------------------------------
# Evidence helpers
# ---------------------------------------------------------------------------

def explicit_strong(features: dict[str, Any]) -> bool:
    return bool(
        features.get("same_entity")
        or features.get("triggered_by")
    )


def context_compatible(a: dict[str, Any], b: dict[str, Any]) -> bool:
    same_app = bool(norm(a.get("app")) and norm(a.get("app")) == norm(b.get("app")))
    same_window = bool(
        norm(a.get("window"))
        and norm(a.get("window")) == norm(b.get("window"))
    )
    same_tab = bool(
        norm(a.get("browser_tab"))
        and norm(a.get("browser_tab")) == norm(b.get("browser_tab"))
    )

    # Same window is the strongest context-only continuity. Same tab without
    # same window is weaker but still useful in a browser.
    return same_window or (same_app and same_tab)


def is_system_unassigned(activity: dict[str, Any]) -> bool:
    layers = {
        str(value).upper()
        for value in activity.get("source_layers", [])
        if isinstance(value, str)
    }

    activity_type = str(activity.get("type", "")).upper()

    # Conservative by design: only agent/system-layer OTHER events are
    # automatically UNASSIGNED. User activity is never discarded merely because
    # the app looks unusual.
    return (
        activity_type in SYSTEM_TYPES
        and layers
        and layers.issubset(SYSTEM_LAYERS)
    )


# ---------------------------------------------------------------------------
# Logical execution state
# ---------------------------------------------------------------------------

class Execution:
    def __init__(
        self,
        session_id: str,
        number: int,
        first_activity: dict[str, Any],
    ) -> None:
        self.session_id = session_id
        self.number = number
        self.execution_id = f"{session_id}:exec-{number:04d}"

        self.activity_ids: list[str] = []
        self.member_indices: list[int] = []
        self.entity_keys: set[tuple[str, str]] = set()

        self.first_dt = first_activity["_start_dt"]
        self.last_dt = first_activity["_end_dt"]

        self.last_app = norm(first_activity.get("app"))
        self.last_window = norm(first_activity.get("window"))
        self.last_tab = norm(first_activity.get("browser_tab"))

        self.segments: list[list[int]] = []
        self._current_segment: list[int] = []

    def add(self, index: int, activity: dict[str, Any]) -> None:
        self.activity_ids.append(activity["activity_id"])
        self.member_indices.append(index)

        for entity in activity.get("entities", []):
            if not isinstance(entity, dict):
                continue
            etype = entity.get("type")
            value = entity.get("value")
            if isinstance(etype, str) and isinstance(value, str):
                self.entity_keys.add((norm(etype), norm(value)))

        self.last_dt = activity["_end_dt"]
        self.last_app = norm(activity.get("app"))
        self.last_window = norm(activity.get("window"))
        self.last_tab = norm(activity.get("browser_tab"))

        self._current_segment.append(index)

    def close_contiguous_segment(self) -> None:
        if self._current_segment:
            self.segments.append(self._current_segment)
            self._current_segment = []

    def finish(self) -> None:
        self.close_contiguous_segment()

    @property
    def member_count(self) -> int:
        return len(self.member_indices)


# ---------------------------------------------------------------------------
# Candidate execution scoring
# ---------------------------------------------------------------------------


def score_context_for_execution(
    current: dict[str, Any],
    execution: Execution,
    activities_by_id: dict[str, dict[str, Any]],
    relationship_index: dict[str, dict[str, dict[str, Any]]],
) -> dict[str, Any] | None:
    """
    Score only very recent contextual continuation.

    Strong relationships are NOT handled here; they are resolved separately
    from the direct relationship index so a process can resume after a long
    interruption without scanning every historical activity.
    """
    if not execution.member_indices:
        return None

    recent_activity_ids = [
        activities_by_id[activity_id]["activity_id"]
        for activity_id in execution.activity_ids[-RECENT_MEMBER_LIMIT:]
    ]

    best: dict[str, Any] | None = None

    for member_id in recent_activity_ids:
        member = activities_by_id[member_id]
        features = relationship_index.get(current["activity_id"], {}).get(member_id)

        if not features:
            continue

        delta = abs(current["_start_ts"] - member["_start_ts"])

        if (
            features.get("score", 0) < CONTEXT_SCORE_MIN
            or delta > CONTEXT_CONTINUATION_MAX_SECONDS
            or not context_compatible(current, member)
        ):
            continue

        candidate = {
            "mode": "CONTEXT",
            "features": features,
            "member_activity_id": member_id,
            "delta_seconds": delta,
        }

        if (
            best is None
            or features.get("score", 0) > best["features"].get("score", 0)
            or (
                features.get("score", 0) == best["features"].get("score", 0)
                and delta < best["delta_seconds"]
            )
        ):
            best = candidate

    return best


def strong_execution_candidates(
    current: dict[str, Any],
    execution_by_activity_id: dict[str, Execution],
    relationship_index: dict[str, dict[str, dict[str, Any]]],
) -> list[tuple[Execution, dict[str, Any]]]:
    """
    Find execution candidates through explicit strong relationship evidence.

    This is intentionally driven by the sparse relationship index, not by
    scanning every historical execution.
    """
    candidates: dict[str, tuple[Execution, dict[str, Any]]] = {}

    for other_activity_id, features in relationship_index.get(
        current["activity_id"], {}
    ).items():
        if not explicit_strong(features):
            continue

        execution = execution_by_activity_id.get(other_activity_id)
        if execution is None:
            continue

        delta = abs(
            current["_start_ts"]
            - execution.last_dt.timestamp()
        )

        # Very long gaps are still allowed when the relation itself is strong,
        # but we cap them to avoid treating stale identifiers as immortal.
        if delta > STRONG_BRIDGE_MAX_SECONDS:
            continue

        candidate = {
            "mode": "STRONG",
            "features": features,
            "member_activity_id": other_activity_id,
            "delta_seconds": delta,
        }

        previous = candidates.get(execution.execution_id)
        if (
            previous is None
            or features.get("score", 0) > previous[1]["features"].get("score", 0)
            or (
                features.get("score", 0) == previous[1]["features"].get("score", 0)
                and delta < previous[1]["delta_seconds"]
            )
        ):
            candidates[execution.execution_id] = (execution, candidate)

    return list(candidates.values())


def reconstruct_session(
    session_id: str,
    activities: list[dict[str, Any]],
    relationship_index: dict[str, dict[str, dict[str, Any]]],
) -> tuple[list[Execution], dict[str, Any]]:
    executions: list[Execution] = []
    execution_by_activity_id: dict[str, Execution] = {}
    active_recent: list[Execution] = []
    next_number = 1

    activities_by_id = {
        activity["activity_id"]: activity
        for activity in activities
    }

    assignment_by_activity: dict[str, str] = {}

    for index, activity in enumerate(activities):
        activity_id = activity["activity_id"]

        if is_system_unassigned(activity):
            assignment_by_activity[activity_id] = "UNASSIGNED"
            for execution in active_recent:
                execution.close_contiguous_segment()
            active_recent = []
            continue

        # ---------------------------------------------------------------
        # Tier 1: explicit entity/trigger relationship
        # ---------------------------------------------------------------
        strong_candidates = strong_execution_candidates(
            activity,
            execution_by_activity_id,
            relationship_index,
        )

        chosen: Execution | None = None
        chosen_evidence: dict[str, Any] | None = None

        if strong_candidates:
            strong_candidates.sort(
                key=lambda item: (
                    item[1]["features"].get("score", 0),
                    -item[1]["delta_seconds"],
                ),
                reverse=True,
            )
            chosen, chosen_evidence = strong_candidates[0]

        # ---------------------------------------------------------------
        # Tier 2: extremely local context continuity
        # ---------------------------------------------------------------
        if chosen is None:
            # Keep only executions whose last activity is close enough to
            # continue locally. Long-range resumption must use Tier 1.
            current_ts = activity["_start_ts"]
            active_recent = [
                execution
                for execution in active_recent
                if current_ts - execution.last_dt.timestamp()
                <= CONTEXT_CONTINUATION_MAX_SECONDS
            ]

            context_candidates: list[tuple[Execution, dict[str, Any]]] = []

            for execution in active_recent:
                evidence = score_context_for_execution(
                    activity,
                    execution,
                    activities_by_id,
                    relationship_index,
                )
                if evidence is not None:
                    context_candidates.append((execution, evidence))

            if context_candidates:
                context_candidates.sort(
                    key=lambda item: (
                        item[1]["features"].get("score", 0),
                        -item[1]["delta_seconds"],
                    ),
                    reverse=True,
                )
                chosen, chosen_evidence = context_candidates[0]

        # ---------------------------------------------------------------
        # Tier 3: start a new logical execution candidate
        # ---------------------------------------------------------------
        if chosen is None:
            chosen = Execution(session_id, next_number, activity)
            next_number += 1
            executions.append(chosen)
        else:
            # Any interruption by another logical execution creates a new
            # contiguous segment, even though the logical execution remains
            # the same.
            if active_recent and active_recent[-1] is not chosen:
                chosen.close_contiguous_segment()

        chosen.add(index, activity)
        execution_by_activity_id[activity_id] = chosen
        assignment_by_activity[activity_id] = chosen.execution_id

        # Rebuild the local active list. The chosen execution is always most
        # recent; other executions survive only while they are locally
        # resumable through context.
        current_ts = activity["_start_ts"]
        active_recent = [
            execution
            for execution in active_recent
            if current_ts - execution.last_dt.timestamp()
            <= CONTEXT_CONTINUATION_MAX_SECONDS
        ]

        if chosen not in active_recent:
            active_recent.append(chosen)
        else:
            active_recent.remove(chosen)
            active_recent.append(chosen)

    for execution in executions:
        execution.finish()

    unassigned_count = sum(
        1
        for value in assignment_by_activity.values()
        if value == "UNASSIGNED"
    )

    summary = {
        "session_id": session_id,
        "activities": len(activities),
        "logical_executions": len(executions),
        "unassigned_activities": unassigned_count,
        "unknown_activities": 0,
        "assigned_activities": len(activities) - unassigned_count,
        "singleton_executions": sum(
            1 for execution in executions if execution.member_count == 1
        ),
    }

    return executions, summary


# ---------------------------------------------------------------------------
# Output conversion
# ---------------------------------------------------------------------------

def execution_record(
    execution: Execution,
    activities: list[dict[str, Any]],
) -> dict[str, Any]:
    first = activities[execution.member_indices[0]]
    last = activities[execution.member_indices[-1]]

    contiguous_segments = []
    for segment_indices in execution.segments:
        if not segment_indices:
            continue

        start_activity = activities[segment_indices[0]]
        end_activity = activities[segment_indices[-1]]

        contiguous_segments.append(
            {
                "start": start_activity["start"],
                "end": end_activity["end"],
                "activity_ids": [
                    activities[i]["activity_id"] for i in segment_indices
                ],
            }
        )

    return {
        "execution_id": execution.execution_id,
        "session_id": execution.session_id,
        "start": first["start"],
        "end": last["end"],
        "activity_ids": execution.activity_ids,
        "segments": contiguous_segments,
    }


def build_segment_records(
    executions: list[Execution],
    activities: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []

    for execution in executions:
        execution.finish()

        for segment_number, indices in enumerate(execution.segments, start=1):
            if not indices:
                continue

            first = activities[indices[0]]
            last = activities[indices[-1]]

            # A single instantaneous activity has no measurable duration.
            # Keep it inside the logical execution record for traceability, but
            # do not emit an invalid zero-length candidate segment. Such
            # activities are intentionally counted in the summary.
            if parse_timestamp(last["end"]) <= parse_timestamp(first["start"]):
                continue

            records.append(
                {
                    "session_id": execution.session_id,
                    "start": first["start"],
                    "end": last["end"],
                    "label": execution.execution_id,
                    "execution_id": execution.execution_id,
                    "segment_number": segment_number,
                    "activity_count": len(indices),
                }
            )

    records.sort(
        key=lambda row: (
            row["session_id"],
            row["start"],
            row["end"],
            row["execution_id"],
        )
    )
    return records


# ---------------------------------------------------------------------------
# Invariants / self-check
# ---------------------------------------------------------------------------

def self_check(
    by_session: dict[str, list[dict[str, Any]]],
    executions_by_session: dict[str, list[Execution]],
    segments: list[dict[str, Any]],
) -> None:
    activity_ids_global: set[str] = set()

    for session_id, activities in by_session.items():
        ids = [a["activity_id"] for a in activities]
        if len(ids) != len(set(ids)):
            raise AssertionError(
                f"Duplicate activity IDs in session {session_id}."
            )

        activity_ids_global.update(ids)

        seen_in_execution: set[str] = set()
        for execution in executions_by_session.get(session_id, []):
            for activity_id in execution.activity_ids:
                if activity_id in seen_in_execution:
                    raise AssertionError(
                        f"Activity assigned twice in session {session_id}: {activity_id}"
                    )
                seen_in_execution.add(activity_id)

        if seen_in_execution:
            missing = set(ids) - seen_in_execution
            # SYSTEM-layer unassigned activities are intentionally absent from
            # logical executions.
            unexpected = {
                activity_id
                for activity_id in missing
                if not any(
                    a["activity_id"] == activity_id
                    and is_system_unassigned(a)
                    for a in activities
                )
            }
            if unexpected:
                raise AssertionError(
                    f"Unexpected unassigned activities in {session_id}: "
                    f"{sorted(unexpected)[:5]}"
                )

    # Segment validity / non-overlap.
    by_segment_session: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for segment in segments:
        if parse_timestamp(segment["end"]) <= parse_timestamp(segment["start"]):
            raise AssertionError(
                f"Non-positive segment: {segment}"
            )
        by_segment_session[segment["session_id"]].append(segment)

    for session_id, rows in by_segment_session.items():
        rows.sort(key=lambda r: parse_timestamp(r["start"]))
        for previous, current in zip(rows, rows[1:]):
            if parse_timestamp(current["start"]) < parse_timestamp(previous["end"]):
                raise AssertionError(
                    f"Overlapping candidate segments in {session_id}: "
                    f"{previous} / {current}"
                )

    # No generated segment may reference a missing activity universe.
    for segment in segments:
        if not isinstance(segment["execution_id"], str):
            raise AssertionError("Segment has invalid execution_id.")


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------

def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(
                json.dumps(record, ensure_ascii=False) + "\n"
            )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Reconstruct constrained logical process executions without modifying inputs."
    )
    parser.add_argument(
        "--activities",
        required=True,
        type=Path,
        help="Read-only activity JSONL input.",
    )
    parser.add_argument(
        "--relationships",
        required=True,
        type=Path,
        help="Read-only relationship JSONL input.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help=(
            "Directory for NEW grouping outputs. The script writes only three "
            "files inside this directory and never modifies the input files."
        ),
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()

    try:
        activity_input = args.activities.resolve()
        relationship_input = args.relationships.resolve()
        output_dir = args.output_dir.resolve()

        if activity_input == relationship_input:
            raise ValueError("Activities and relationships inputs must be different files.")

        output_dir.mkdir(parents=True, exist_ok=True)

        executions_output = output_dir / "executions.jsonl"
        segments_output = output_dir / "segments_candidates.jsonl"
        summary_output = output_dir / "grouping_summary.json"

        # Hard safety guard: never allow an output file to equal an input file.
        input_paths = {activity_input, relationship_input}
        output_paths = {executions_output, segments_output, summary_output}
        collision = input_paths.intersection(output_paths)
        if collision:
            raise ValueError(
                "Refusing to overwrite an input file: "
                + ", ".join(str(path) for path in sorted(collision))
            )

        if not activity_input.exists():
            raise FileNotFoundError(activity_input)
        if not relationship_input.exists():
            raise FileNotFoundError(relationship_input)

        activity_records = load_jsonl(activity_input)
        relationship_records = load_jsonl(relationship_input)

        by_session = validate_activities(activity_records)
        relationship_index = build_relationship_index(relationship_records)

        executions_by_session: dict[str, list[Execution]] = {}
        session_summaries: list[dict[str, Any]] = []
        all_execution_records: list[dict[str, Any]] = []
        all_segments: list[dict[str, Any]] = []

        for session_id, activities in sorted(by_session.items()):
            executions, summary = reconstruct_session(
                session_id,
                activities,
                relationship_index,
            )

            executions_by_session[session_id] = executions
            session_summaries.append(summary)

            for execution in executions:
                all_execution_records.append(
                    execution_record(execution, activities)
                )

            all_segments.extend(
                build_segment_records(executions, activities)
            )

        self_check(by_session, executions_by_session, all_segments)

        instantaneous_execution_count = 0
        for session_id, session_executions in executions_by_session.items():
            session_activities = by_session[session_id]
            for execution in session_executions:
                for indices in execution.segments:
                    if len(indices) != 1:
                        continue
                    only_activity = session_activities[indices[0]]
                    if parse_timestamp(only_activity["end"]) <= parse_timestamp(only_activity["start"]):
                        instantaneous_execution_count += 1

        output_summary = {
            "sessions": len(by_session),
            "activities": len(activity_records),
            "logical_executions": len(all_execution_records),
            "candidate_segments": len(all_segments),
            "instantaneous_segments_skipped": instantaneous_execution_count,
            "unassigned_activities": sum(
                row["unassigned_activities"] for row in session_summaries
            ),
            "singleton_executions": sum(
                row["singleton_executions"] for row in session_summaries
            ),
            "parameters": {
                "strong_bridge_max_seconds": STRONG_BRIDGE_MAX_SECONDS,
                "context_continuation_max_seconds": CONTEXT_CONTINUATION_MAX_SECONDS,
                "recent_member_limit": RECENT_MEMBER_LIMIT,
                "context_score_min": CONTEXT_SCORE_MIN,
                "strong_score_margin": STRONG_SCORE_MARGIN,
            },
            "inputs": {
                "activities": str(activity_input),
                "relationships": str(relationship_input),
            },
            "self_check": "PASS",
            "session_summaries": session_summaries,
        }

        write_jsonl(executions_output, all_execution_records)
        write_jsonl(segments_output, all_segments)

        with summary_output.open("w", encoding="utf-8") as handle:
            json.dump(
                output_summary,
                handle,
                ensure_ascii=False,
                indent=2,
            )
            handle.write("\n")

    except (OSError, ValueError, AssertionError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print("PROCESS RECONSTRUCTION")
    print("=" * 64)
    print(f"Sessions:                {len(by_session)}")
    print(f"Activities:              {len(activity_records)}")
    print(f"Logical executions:      {len(all_execution_records)}")
    print(f"Candidate segments:      {len(all_segments)}")
    print(
        "UNASSIGNED activities:   "
        f"{output_summary['unassigned_activities']}"
    )
    print(
        "Singleton executions:    "
        f"{output_summary['singleton_executions']}"
    )
    print()
    print("Self-check: PASS")
    print(f"Inputs untouched:        YES")
    print(f"Wrote outputs to:        {output_dir}")
    print(f"  executions:            {executions_output.name}")
    print(f"  segments:              {segments_output.name}")
    print(f"  summary:               {summary_output.name}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
